env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
  - airbnb-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules: { "@typescript-eslint/no-unused-vars": warn, "arrow-body-style": 0 }
settings:
  import/resolver:
    node: true
    typescript: true
    airbnb-typescript: true
    alias:
      extensions:
        - ".js"
        - ".jsx"
      map:
        - - "@"
          - "."
